FROM python:latest
RUN apt-get update && apt-get install -y curl \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && ln -s /root/.local/bin/poetry /usr/local/bin/poetry

RUN mkdir -p /dbt/NBA
WORKDIR /dbt/NBA
COPY ./NBA_dbt/poetry.lock ./NBA_dbt/pyproject.toml ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction --no-ansi

ENTRYPOINT [ "sleep", "infinity" ]