FROM python:latest
RUN apt-get update && apt-get install -y curl \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && ln -s /root/.local/bin/poetry /usr/local/bin/poetry

RUN mkdir -p /app/django
WORKDIR /app/NBA_backend
COPY ./NBA_backend/poetry.lock ./NBA_backend/pyproject.toml ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction --no-ansi

ENTRYPOINT [ "sleep", "infinity" ]